### ISSUE TITLE
Player Warnings

### ISSUE THREAD

**Issue by freddinator** [andimage/PCBridge#10]
It's been suggested on the forums a few times to create a player warning system, so staff can leave notes on a player.
- /warn [player] new [message] - Create a new warning for the player. The player would be sent a notification that they have been warned for something.
- /warn player silent [message] - Warn without a message
- /warn list [player] - List a player's warnings

Possible format:

> **Warnings for TheOctopus**
> Warned by Ouhai_Ruby on 7th June 2016: Minor grief
> Warned by _andy on 19th June 2016: Being rude

When a player joins, it could also send a message to online staff saying something like

> Player TheOctopus has 2 warnings

I'd assume we'd also want a web interface on the new site. Perhaps this could be unified with forum warnings, so infractions in-game and on the forums can be seen?

**Comment by andimage** [comment]
Nice one. I'll work on that next.

Should the warnings actually have any bearing or are they purely just for record keeping? For example, staff receive a message when a player with X number of warnings logs in, etc.

**Comment by andimage** [comment]
Ignore my last comment. I totally missed that part in your post
