### ISSUE TITLE
Keep removed bans in database

### ISSUE THREAD

**Issue by freddinator** [andimage/PCBridge#4]
Just a suggestion, when a player is unbanned (or the ban expires), it is not actually removed from the database, but a boolean column is set to being invalid and the uuid of the unbanning staff is recorded.

This solves the following problem:
* Player gets tempbanned for a minor offence
* Player's ban expires
* Player commits minor offence again
* Nobody knows this happened, because the ban record was deleted

This would also allow for staff to check who unbanned a player in the case of a malicious unban.

**Comment by andimage** [comment]
At the moment it does exactly that except for recording the unbanning staff. I'll add that in, thanks

**Comment by freddinator** [comment]
It would also be helpful to have a command for this, /lookup history [player] maybe?

**Comment by andimage** [comment]
/lookup history [player] currently looks up their name change history via the Mojang web API. I'm thinking of putting the past ban record data into /checkban [player]

**Comment by freddinator** [comment]
I'm thinking it might be better to put all of that stuff in one command, /lookup [player], as this fits with a lot of the existing commands. For example: /whois [player] shows you all of the player's info, or /seen [player] tells you when they were last on and their IP address. It would make looking up data  a lot easier if it was just one command.
